package ai.aistem.xbot.framework.message;

/**
 * @author: aistem
 * @created: 2018/5/30/10:38
 * @desc: DCMessage
 */
public interface DCMessage {

    String ACTION_UNDEFINED = "ACTION_UNDEFINED";

    //语音命令广播
    String ACTION_VOICE_CONTROL_COMMAND = "com.aistem.ACTION_VOICE_CONTROL_COMMAND";
    String EXTRA_VOICE_CONTROL_COMMAND = "com.aistem.EXTRA_VOICE_CONTROL_COMMAND";
    //语音命令：
    //1. 唤醒
    String VOICE_CONTROL_COMMAND_WAKEUP = "VOICE_CONTROL_COMMAND_WAKEUP";
    String VOICE_CONTROL_COMMAND_READ = "VOICE_CONTROL_COMMAND_READ";
    String VOICE_CONTROL_COMMAND_EXIT = "VOICE_CONTROL_COMMAND_EXIT";

    String ACTION_CHAT_MAG_COMMAND = "com.aistem.ACTION_CHAT_MAG_COMMAND";
    String EXTRA_CHAT_MAG_COMMAND = "com.aistem.EXTRA_CHAT_MAG_COMMAND";
    //String ACTION_CHAT_MAG_COMMAND="com.aistem.ACTION_CHAT_MAG_COMMAND";
    //String EXTRA_CHAT_MAG_COMMAND="com.aistem.EXTRA_CHAT_MAG_COMMAND";
    String EXTRA_CHAT_VOICE_MAG_COMMAND = "com.aistem.EXTRA_CHAT_VOICE_MAG_COMMAND";

    //随机闲聊表情标识广播
    String ACTION_SELF_TALK_FACEID_COMMAND = "com.xbot.ACTION_SELF_TALK_FACEID_COMMAND";
    String EXTRA_SELF_TALK_FACEID_COMMAND = "com.xbot.EXTRA_SELF_TALK_FACEID_COMMAND";

    //MQTT连接/订阅/发布广播
    String ACTION_MQTT_CLIENT_COMMAND = "com.xbot.ACTION_MQTT_CLIENT_COMMAND";
    String EXTRA_MQTT_CLIENT_COMMAND = "com.xbot.EXTRA_MQTT_CLIENT_COMMAND";

    //蜜语文字广播
    String ACTION_CHAT_TEXT_COMMAND = "com.xbot.ACTION_CHAT_TEXT_COMMAND";
    String EXTRA_CHAT_TEXT_COMMAND = "com.xbot.EXTRA_CHAT_TEXT_COMMAND";

    //蜜语表情时长广播
    String ACTION_CHAT_FACE_COMMAND = "com.xbot.ACTION_CHAT_FACE_COMMAND";
    String EXTRA_CHAT_FACE_COMMAND = "com.xbot.EXTRA_CHAT_FACE_COMMAND";

    //闲聊时长广播
    String ACTION_CHAT_DURATION_COMMAND = "com.xbot.ACTION_CHAT_DURATION_COMMAND";
    String EXTRA_CHAT_DURATION_COMMAND = "com.xbot.EXTRA_CHAT_DURATION_COMMAND";

    //磨耳朵单曲推送广播
    String ACTION_SOUND_VOICE_COMMAND = "com.xbot.ACTION_SOUND_VOICE_COMMAND";
    String EXTRA_SOUND_VOICE_COMMAND = "com.xbot.EXTRA_SOUND_VOICE_COMMAND";

    //磨耳朵专辑推送广播
    String ACTION_SOUND_ALBUM_COMMAND = "com.xbot.ACTION_SOUND_ALBUM_COMMAND";
    String EXTRA_SOUND_ALBUM_COMMAND = "com.xbot.EXTRA_SOUND_ALBUM_COMMAND";

    //网络音频资源列表广播
    String ACTION_NET_PLAYLIST_COMMAND = "com.xbot.ACTION_NET_PLAYLIST_COMMAND";
    String EXTRA_NET_PLAYLIST_COMMAND = "com.xbot.EXTRA_NET_PLAYLIST_COMMAND";

    //绑定新用户广播
    String ACTION_BIND_USER_COMMAND = "com.xbot.ACTION_BIND_USER_COMMAND";
    String EXTRA_BIND_USER_COMMAND = "com.xbot.EXTRA_BIND_USER_COMMAND";
    //夜间设置广播
    String ACTION_SET_NIGHT_COMMAND = "com.xbot.ACTION_SET_NIGHT_COMMAND";
    String EXTRA_SET_NIGHT_COMMAND = "com.xbot.EXTRA_SET_NIGHT_COMMAND";
    //夜间状态广播
    String ACTION_NIGHT_STATE_COMMAND = "com.xbot.ACTION_NIGHT_STATE_COMMAND";
    String EXTRA_NIGHT_STATE_COMMAND = "com.xbot.EXTRA_NIGHT_STATE_COMMAND";

    //夜间模式结束
    String ACTION_NIGHT_STATE_FINISH_COMMAND = "com.xbot.ACTION_NIGHT_STATE_FINISH_COMMAND";
    String EXTRA_NIGHT_STATE_FINISH_COMMAND = "com.xbot.EXTRA_NIGHT_STATE_FINISH_COMMAND";

    //防沉迷设置广播
    String ACTION_SET_ANTI_ADDICTION_COMMAND = "com.xbot.ACTION_SET_ANTI_ADDICTION_COMMAND";
    String EXTRA_SET_ANTI_ADDICTION_COMMAND = "com.xbot.EXTRA_SET_ANTI_ADDICTION_COMMAND";
    //防沉迷状态广播
    String ACTION_ANTI_ADDICTION_STATE_COMMAND = "com.xbot.ACTION_ANTI_ADDICTION_STATE_COMMAND";
    String EXTRA_ANTI_ADDICTION_STATE_COMMAND = "com.xbot.EXTRA_ANTI_ADDICTION_STATE_COMMAND";
    //防沉迷准备开始和准备结束广播
    String ACTION_PRE_ANTI_ADDICTION_STATE_COMMAND = "com.xbot.ACTION_PRE_ANTI_ADDICTION_STATE_COMMAND";
    String EXTRA_PRE_ANTI_ADDICTION_STATE_COMMAND = "com.xbot.EXTRA_PRE_ANTI_ADDICTION_STATE_COMMAND";
    //闲聊待机状态广播
    String ACTION_SELF_TALK_STATE_COMMAND = "com.xbot.ACTION_SELF_TALK_STATE_COMMAND";
    String EXTRA_SELF_TALK_STATE_COMMAND = "com.xbot.EXTRA_SELF_TALK_STATE_COMMAND";
    //聊天状态广播
    String ACTION_CHAT_STATE_COMMAND = "com.xbot.ACTION_CHAT_STATE_COMMAND";
    String EXTRA_CHAT_STATE_COMMAND = "com.xbot.EXTRA_CHAT_STATE_COMMAND";
    //休眠状态广播
    String ACTION_SLEEP_STATE_COMMAND = "com.xbot.ACTION_SLEEP_STATE_COMMAND";
    String EXTRA_SLEEP_STATE_COMMAND = "com.xbot.EXTRA_SLEEP_STATE_COMMAND";
    //工作状态广播
    String ACTION_WORK_STATE_COMMAND = "com.xbot.ACTION_WORK_STATE_COMMAND";
    String EXTRA_WORK_STATE_COMMAND = "com.xbot.EXTRA_WORK_STATE_COMMAND";
    //基础状态广播
    String ACTION_BASE_STATE_COMMAND = "com.xbot.ACTION_BASE_STATE_COMMAND";
    String EXTRA_BASE_STATE_COMMAND = "com.xbot.EXTRA_BASE_STATE_COMMAND";

    //更新SharedPreferences广播
    String ACTION_UPDATE_SP_COMMAND = "com.xbot.ACTION_UPDATE_SP_COMMAND";
    String EXTRA_UPDATE_SP_COMMAND = "com.xbot.EXTRA_UPDATE_SP_COMMAND";

    //夜间模式开始/结束（闹钟）广播
    String ACTION_NIGHT_ALARM_COMMAND = "com.xbot.ACTION_NIGHT_ALARM_COMMAND";
    String EXTRA_NIGHT_ALARM_COMMAND = "com.xbot.EXTRA_NIGHT_ALARM_COMMAND";

    //头顶键触摸广播
    String ACTION_TOUCH_ABBE_HEAD_COMMAND = "com.xbot.ACTION_TOUCH_ABBE_HEAD_COMMAND";
    String EXTRA_TOUCH_ABBE_HEAD_COMMAND = "com.xbot.EXTRA_TOUCH_ABBE_HEAD_COMMAND";

    //无操作超时广播
    String ACTION_NOP_TIMEOUT_COMMAND = "com.xbot.ACTION_NOP_TIMEOUT_COMMAND";
    String EXTRA_NOP_TIMEOUT_COMMAND = "com.xbot.EXTRA_NOP_TIMEOUT_COMMAND";


    //距离传感器
    String CUSTOM_PROXIMITY_TRIGGER = "android.intent.custom.proximity_trigger";
    //ProximityTiggerIntent.putExtra("status", isNear);
}
